### ISSUE TITLE
setsummary does not work like it should

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon#100]
Passing the parameter
<summary><fields><field name="title">Sensenmann</field></fields></summary>

yields:
<summary>&lt;summary&gt;&lt;fields&gt;&lt;field name="title"&gt;Sensenmann&lt;/field&gt;&lt;/fields&gt;&lt;/summary&gt;</summary>

Instead, it should be like what was passed (as XML, not as text content). Presumably, the passed para is written as InnerText to the summary element (instead of taking the XML document and setting the summary field value to it)

**Comment by boris-horner** [comment]
Above, I inserted XML code but it got scrambled by the CMS, what was wrong now looks right.

Current status: I pass an XML structure with <summary/> as top level element. The summary element contains what was passed as TEXT (with entities for the special XML characters). Instead, it should of course return XML. Of course, I could interpret the data as such, but that was not the idea :-)

**Comment by boris-horner** [comment]
m(  

... with &lt;summary/&gt; as top level element.

**Comment by dewarim** [comment]
Fixed - summary is now returned as XML node.
Note: the client should store summary content with a root node of  \<summary>...</summary>
