### ISSUE TITLE
Change Trigger list in administration has no icons

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon#103]
The yes and no icons are missing. Instead, a quite bulky text is displayed.

1) The icons should be there.
2) The text "Dieses Feld ist markiert oder aktiviert" should be replaced with "ja" / "yes" - the other one with "nein" / "no". Just in case, the icons are missing for whatever reason.

**Comment by dewarim** [comment]
Fixed - icons are included as image:data-url so they won't go missing when the next Asset-Plugin-Update breaks links again.

**Comment by dewarim** [comment]
(note: messages have not been replaced. The messages are clunky, but I hope they are better for people with impaired vision to whom yes/no texts will perhaps not be as helpful. But this is not a final decision, I am open to further discussion in a new issue ;) )

**Comment by boris-horner** [comment]
I don't get the point. How do these text monsters improve anything for the visually handicapped? BTW: making things barrier-free means also that there shouldn't be barriers for people without a handicap either...
