### ISSUE TITLE
HasSubfolders has a different logic about links than GetSubfolders

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon#161]
If a folder has one subfolder and one linked subfolder, getsubfolders returns both, and hassubfolders is true, because there is one real folder.

If there is only the linked subfolder inside, getsubfolders returns the linked folder, but hassubfolders is false.

This is more than cosmetic. Since the + is missing in the tree when displaying a folder structure, it is impossible to navigate into the linked folder in the tree view, if no real subfolder is also present. At least, it's confusing. 

Suggestion: let hassubfolders also count the linked subfolders.

**Comment by dewarim** [comment]
Fixed in cinnamon-db: https://github.com/dewarim/cinnamon-db/commit/54369920c7162843003612156ca06657f6e48d42
