### ISSUE TITLE
Deleting user does not remove user group

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon#184]
Creating a user creates a user group associated with that user. 

Deleting the user requires transferring the assets to another user - typically the admin. However, deleting the user does not remove the initially created user group, but transferring the assets assigns the new user_id to the user group in the table groups_users.

The desired behaviour is that deleting the user also removes the user_group --> user association in the group_users table.

**Comment by dewarim** [comment]
Do we still need the group membership transfer at all?
