### ISSUE TITLE
copy command creates an object that references all original metasets

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon#190]
The API command "copy" creates a clone of the original object.

The new object references the same metasets as the original, so changes to the metadata in one object apply to all copies. Since templates are also based on topics, this is very annoying, and there is no good workaround. It is possible to patch this in the client libraries (by explicitely cloning the metasets after copy) but this would impede performance and I would prefer to avoid this.

**Comment by dewarim** [comment]
Looks like the source of the problem is in OsdController.copy() calling copyMetastes, which only links but not copies the metasets:

`    public void copyMetasets(IMetasetOwner source, IMetasetOwner target, String metasets) {
        if (metasets == null) {
            for (Metaset m : source.fetchMetasets()) {
                log.debug(String.format("Add Metaset %d %s from %d to %d", m.getId(), m.getType().getName(), source.getId(), target.getId()));
                target.addMetaset(m);
            }
        } else {
            for (String metasetName : metasets.split(",")) {
                Metaset metaset = source.fetchMetaset(metasetName);
                target.addMetaset(metaset);
            }
        }
    }`

**Comment by dewarim** [comment]
And the problem exists in copyFolders, too. see #191
