### ISSUE TITLE
Error saving object metadata

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon#98]
![errormessage](https://cloud.githubusercontent.com/assets/4948244/11440090/f67039fc-94ff-11e5-8139-3c7b841dc892.png)

When setting the metadata of an object, I get the error message in the screenshot. Obviously, the system tries to create a summary element in the wrong place (perhaps in a metaset DOM doc?).

**Comment by dewarim** [comment]
Which screenshot?

**Comment by dewarim** [comment]
should work now.
